# Generated by Django 4.2.1 on 2023-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorreccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='categoria',
            field=models.IntegerField(default='valor_ejemplo'),
            preserve_default=False,
        ),
    ]
