# Generated by Django 4.2.1 on 2023-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorreccion', '0003_alter_clase_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
    ]
